# Generated by Django 2.2.5 on 2020-02-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200215_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('pending', 'Pending')], default='pending', max_length=12),
        ),
    ]
